//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TdtBaiKiemTraGK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ketqua
    {
        public string MaSV { get; set; }
        public Nullable<int> MaMH { get; set; }
        public string Diem { get; set; }
    }
}
